### ISSUE TITLE
ImageMagick draw problem after upgrade to ImageMagick7.x86_64 7.0.8.66-1.el7.remi

### ISSUE THREAD

**Issue by mohsen** [remicollet/remirepo#127]
Hi there,
There is a problem with `-draw` functionality of ImageMagick (`convert`) after upgrading to the latest version from remi repo. Unfortunately doing a `yum downgrade` does not fix the problem and I don't know which special package causes this problem.
I first thought that this is related to fonts being removed from my centos 7. `convert -list font` tells us the list of font names, so the font is actually available. Here is the sample issue:
`$ convert in.jpg -draw "gravity southwest text 84,12'Some Text" out.jpg`

only 'See' is printed on the image and other characters are ignored!

**Comment by remicollet** [comment]
I can reproduce on C7, but works fine on F29, so looks like some fonts are missing
Need investigation....

**Comment by mohsen** [comment]
Thanks for the reply. Very strange behavior because from each 3 letters in draw, one is printed. Maybe it's related to a buggy 3-byte UTF-8 decoding of the input text?

**Comment by remicollet** [comment]
Indeed... ABCDEFGHIJKLM is printed as ADGJ

**Comment by remicollet** [comment]
Ok, this is related to gslib delegation

Since 6.9.10-65 and 7.0.8.65, I drop gslilb usage because of new bug introduced in 7.7
https://bugzilla.redhat.com/1753534

Rebuild using --with-gslib fixes this issues, but the file description leak can be terrible, especially for web env (php-pecl-imagick)

Working on a workaround.

**Comment by remicollet** [comment]
Fixed by:

**libpaper-1.1.24-8.el8.remi**
https://git.remirepo.net/cgit/rpms/lib/libpaper.git/commit/?id=ae853c7a30c94a4a647588f8f5b41d4f0bb27f08

**ImageMagick6-6.9.10.66-2**
https://git.remirepo.net/cgit/rpms/ImageMagick6.git/commit/?id=2c11bf7fb94d6e222091eb7daac7f6b1c7575e79

**ImageMagick7-7.0.8.66-2**
https://git.remirepo.net/cgit/rpms/ImageMagick7.git/commit/?id=40fd9fe2f07f57cf0714fc21bd9553225ea9af25

Notice: **libpaper** update, which fix a file descriptor leak is only in "remi" (as it overrides default buggy version in base it can't go to "remi-safe")

Feedback welcome.

**Comment by mohsen** [comment]
I cannot see any update on the repository:

`yum clean expire-cache`
`yum update --enablerepo=remi`

**Comment by remicollet** [comment]
Wait for mirror to be synced
Or download from primary server

**Comment by mohsen** [comment]
Thanks for your quick help. Updated from the primary server and works fine here.
Regards.
