### ISSUE TITLE
PHP 7.4 packages for CentOS 6

### ISSUE THREAD

**Issue by tomsommer** [remicollet/remirepo#131]
CentOS 6 is EOL in November 2020 - it would be really nice to have PHP 7.4 support until then.

**Comment by remicollet** [comment]
Sorry, PHP 7.2 and 7.3 was already a terrible nightmare
https://twitter.com/RemiCollet/status/903155214441738240

As C6 is <1 year before its EOL, I don't plan to even try to build 7.4 for it
There is realloy too much outdated libraries, and I cannot mange all of them.

You REALLY have to plan the upgrade to C7 or C8

**Comment by remicollet** [comment]
For memory, download statistics (on 7.3)
* EL-6 : **7%** decreasing
* EL-7 : **84%**
* EL-8: **7%** increasing

**Comment by dterweij** [comment]
Hmm okay, so my old still running fine centos 6 server will stop serving new wordpress versions because they are going to change the minimum of php to 7.4. That is sad... Now I am going to have a big road to think about a linux upgrade. it wont be centos, that i know for sure but the upgrade path to al my custom changes and scripts will be a big pain as well as openvz VM's that are running on the server. I realy hate "new" OS versions. Most of the time there is no seamless upgrade path. Why is there not a linux distribution with updates forever? That i sm look for for years now.

**Comment by remicollet** [comment]
@dterweij seriously ?

Enterprise Linux is maintained for **10 years** (even 13 for RHEL)

>  Why is there not a linux distribution with updates forever?

How much are you ready to pay for doing this work ?
