### ISSUE TITLE
php74-php-geos? 

### ISSUE THREAD

**Issue by tjbx** [remicollet/remirepo#147]
Not sure if this is the best place to ask. I'm trying to figure out why php-geos is not in the repo for php74 for CentOS 7 - it is for php71, php72, and php73. Is it not compatible? Seems like the actual php-geos project hasn't been updated in about two years. 

Also, do you ever get any requests for php-mapserver now that php support had returned in the latest versions?

**Comment by remicollet** [comment]
> Not sure if this is the best place to ask.

It is.

> why php-geos is not in the repo for php74

Because I forgot to rebuild it during the mass rebuild ;)

It is now available.

> Also, do you ever get any requests for php-mapserver now that php support had returned in the latest versions?

No, no request for it for years
and, this one is a nightmare, not a real extension, only some sub-package of mapserver, so need really lot of stuff to split it out.... and swing.... grr...

If you need it, please file another issue, to keep this one for geos.

**Comment by remicollet** [comment]
Package added, so closing
