### ISSUE TITLE
Composer does not work in F35 PHP 7.4 module

### ISSUE THREAD

**Issue by janzeleny** [remicollet/remirepo#196]
Hi Remi,
The composer package there has a dependency on php-symfony4-console which, however, uses some PHP 8 functions. In particular, I am getting traceback trying to run composer (even simple --help) because str_contains() is used in the code. I was not able to test with php-symfony3-console but checking the code, it uses strpos() instead.

Not sure what the right solution is, perhaps switch the dependency to its symfony3 version?

Thanks in advance,
Jan

**Comment by remicollet** [comment]
Explanation: at build time, symfony add dependencies according to current PHP version
So symfony/polyfill-php80 is not added on F35/EL9 where PHP 8 is used

Should be fixed by https://git.remirepo.net/cgit/rpms/php/symfony/php-symfony4.git/commit/?id=3560f36bb024b18c8136c1789a3a4148f04607dd

Please try with latest php-symfony4-4.4.36-2 which is now in the repository

On a minimal install
```
$ php -v
PHP 7.4.27 (cli) (built: Dec 14 2021 17:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ composer  --version
Composer 2.2.4 2022-01-08 12:30:42

```

**Comment by remicollet** [comment]
Notice: as Fedora 35 provides PHP 8 as the default version, supporting an older version is only a best effort.

**Comment by remicollet** [comment]
no feedback so closing
