### ISSUE TITLE
Update uwsgi-plugin-php

### ISSUE THREAD

**Issue by amon-ra** [remicollet/remirepo#209]
Please apply the patch:
https://github.com/unbit/uwsgi/pull/2400

To fix php 8.1

**Comment by remicollet** [comment]
Fixed by
*  https://git.remirepo.net/cgit/rpms/uwsgi/uwsgi-plugin-php.git/commit/?id=9b562493bca17012f082ef94685935e71174bb38 
* *https://git.remirepo.net/cgit/rpms/uwsgi/uwsgi-plugin-php.git/commit/?id=acaddc96ccc610d6fe4f1a24c89915c1974009d1

Version **2.0.20-2** built and uploaded in the repository for **Fedora and EL >= 8**

I also add the EL-9 builds which were missing (uwsgi was not yet available in EPEL-9)

Please remind that uwsgi is no more an active project:

> Note: The project is in maintenance mode (only bugfixes and updates for new languages apis)

(don't really understand the need nowadays, with php-fpm usable from various web-server)
