### ISSUE TITLE
roundcubemail-1.4.14 missing

### ISSUE THREAD

**Issue by davidhrbac** [remicollet/remirepo#244]
There's a new security release of Roundcube 1.4.14, see https://github.com/roundcube/roundcubemail/releases/tag/1.4.14

**Comment by remicollet** [comment]
Current version is 1.6.3

Older versions are 1.4 or 1.5 are not in the repository

**Comment by davidhrbac** [comment]
Well, that's sad, 1.4 is LTS and I have just created a SPEC patch :smile:

**Comment by davidhrbac** [comment]
It used to be there, at least in January.
```bash
grep round /var/log/yum.log*
/var/log/yum.log-20210312:Mar 11 15:43:10 Installed: roundcubemail-1.4.11-1.el7.remi.noarch
/var/log/yum.log-20230101:Jan 09 21:41:23 Updated: roundcubemail-1.4.13-1.el7.remi.noarch
```

**Comment by remicollet** [comment]
I understand the need to not urge users to update... but 
- 1.5 is ~2 years old
- 1.6 is  ~1year old

How much time is reasonable for an update?

And 1.4 uses old packaging using system libraries, which are not really maintained anymore, as since 1.5, everything is bundled in the main packages. Also, dependencies may be missing in some distro.

Also EL-7 is close to its end of life, you should really consider upgrading to EL-8 or EL-9

**Comment by davidhrbac** [comment]
OK

**Comment by remicollet** [comment]
I didn't say I don't want to provide it, only that I what to understand why a such outdated version is still used.

- Version **1.5.4** is now in the repository
- version **1.4.14** is also in the repository for EL-7 and EL-8 only because of dependency on PHP 7

I also updated php-pear-crypt-gpg to 1.6.7 (security update), haven't check other dependencies.

**Comment by davidhrbac** [comment]
Well, thank you. It is not about it being old, but considered 1.4.x and 1.5.x stable (LTS). It is also good to have it in the repo so everyone can easily update to 1.6 as like 1.4 to 1.5 to 1.6. Thanks!

PS: You made me to create a RPM patch after quite a long time and it reminds me I have to shut Repoforge finally...
