### ISSUE TITLE
When will redis 7.4.1 be released? 

### ISSUE THREAD

**Issue by RobinDuhan** [remicollet/remirepo#277]
Hi,

When would you release Redis 7.4.1 for rpm? Since the version has been out for some time and fixes certain important CVEs. I also don't mind contributing if you don't have time.

**Comment by remicollet** [comment]
> When would you release Redis 7.4.1 for rpm?

Short answer: never

Long answer: redis project changed its license and is no more OpenSource

Read: https://redis.io/blog/redis-adopts-dual-source-available-licensing/

Fedora has dropped redis from its repository in F41
RHEL-10 will also remove it

Various alternatives exist, ValKey being the one chosen by Fedora/RHEL
See https://valkey.io/

I encourage you to switch to this OpenSource compatible solution

So redis 7.2, the last OpenSource version, will be le last in the repository

> Since the version has been out for some time and fixes certain important CVEs. 

All CVEs are fixed in **7.2.16** which is still supported

**Comment by RobinDuhan** [comment]
Thanks for responding so quickly. I think you meant 7.2.6 instead of 7.2.16.

**Comment by remicollet** [comment]
> Thanks for responding so quickly. I think you meant 7.2.6 instead of 7.2.16.

Yes, **7.2.6** or **6.2.16** are the last released versions

**Comment by northerngit** [comment]
Thanks for the clarification @remicollet - are there any plans to add ValKey to your repo?  EPEL doesn't seem to have the latest releases for EL8 and Percona appears to be in perpetual testing.

**Comment by remicollet** [comment]
> are there any plans to add ValKey to your repo? 

Not for now
(especially because the "compact" package, and its migration script seems a terrible idea)

**Comment by remicollet** [comment]
As I said, I have no plan to provide valley build
I prefer to concentrate my time on PHP stacks

Closing as the question was about redis and was answered.

**Comment by RobinDuhan** [comment]
@remicollet Is the process of building the package opensource - if so, could you share the reference? Maybe the spec file if that's what you were using. Have to build redis until we migrate to valkey.
