### ISSUE TITLE
libcouchbase does not load plugins

### ISSUE THREAD

**Issue by avsej** [remicollet/remirepo#89]
Hi @remicollet. I fixed issue in Fedora repository
https://src.fedoraproject.org/rpms/libcouchbase/c/bc59f2f986ab99f4d192dad19f06a6d0b7308be2

Upstream will be fixed later during migration to new layout (right now it still install plugins into libdir)

**Comment by remicollet** [comment]
Thanks for the notice.

BTW, I usually monitor fedora changes for package which are backports of Fedora one ;)
BTW, commit notification doesn't always work for newly approved packages :(

Fixed by:
https://git.remirepo.net/cgit/rpms/lib/libcouchbase.git/commit/?id=2f0df9917f667453b12c8669c9ab37c4f37fa41e
https://git.remirepo.net/cgit/rpms/lib/libcouchbase.git/commit/?id=db482c2c27dcc3d92afc003cb087429de4ffe2fb

**Comment by remicollet** [comment]
New build pushed to the repository

Thanks again.
